In [1]:
import numpy as np

## 1. DataTypes and Attributes

In [2]:
#Main data type is ndarray (n-dimension array)
array1 = np.array([1,2,3,4,5])
type(array1)

numpy.ndarray

In [3]:
array2 = np.array([[1,2,3], [4,5,6]])
array2.shape

(2, 3)

In [4]:
array3 = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[13,14,15], [16,17,18]] ])
array3.shape

(3, 2, 3)

In [5]:
array1.ndim, array2.ndim, array3.ndim #number of dimensions of different arrays

(1, 2, 3)

In [6]:
array1.size, array2.size, array3.size #number of elements in different arrays

(5, 6, 18)

## 2. Creating Different kind of NumPy Arrays

In [7]:
sample_array = np.array([1,2,3])
sample_array.dtype

dtype('int64')

In [8]:
ones = np.ones(sample_array.shape) #replace all elements with 1
ones

array([1., 1., 1.])

In [9]:
zeros = np.zeros((2, 3)) #replace all element with 0. (2,3) is a given shape for the new array
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
ones.dtype, zeros.dtype #data type of ones and zeroes are float by default

(dtype('float64'), dtype('float64'))

In [11]:
range_array = np.arange(2, 10, 2) #parameters are: start_from, end_before, steps
range_array

array([2, 4, 6, 8])

In [12]:
random_array = np.random.randint(1, 10, size=(2,3)) #parameters: lowest_number(inclusive), highest_number(exclusive: n-1), size: row, column
random_array

array([[8, 1, 7],
       [2, 9, 2]])

In [13]:
random_array.shape

(2, 3)

In [14]:
random_array_2 = np.random.random((3, 4)) #only shape is passed as argument. low and high is 0.0 and 1.0 by default
random_array_2

array([[0.75283486, 0.16664565, 0.87539328, 0.0856179 ],
       [0.45238197, 0.29835102, 0.47792165, 0.37421478],
       [0.80057435, 0.90026064, 0.73652633, 0.26556578]])

In [15]:
random_array_3 = np.random.rand(3, 4) #same as before
random_array_3

array([[0.16599227, 0.51319901, 0.99643395, 0.30322081],
       [0.90001004, 0.95441021, 0.9243208 , 0.23094684],
       [0.56489479, 0.05294789, 0.47495197, 0.62458861]])

In [16]:
#Pseudo Random Number
np.random.seed(5) #seed functions lock the numbers. So it will produce the exact same random numbers every single time
random_array_4 = np.random.randint(1, 5, size=(2,3))
random_array_4

array([[4, 3, 4],
       [2, 3, 3]])

## 3. Viewing Arrays and Matrices

In [17]:
# view the unique numbers of an array (numbers without repeatation)
np.unique(random_array)

array([1, 2, 7, 8, 9])

In [18]:
array2[0][0]

1

## 4. Manipulating and Comparing Arrays

In [21]:
new_ones = np.ones(array1.shape)
new_ones

array([1., 1., 1., 1., 1.])

In [22]:
array1 + new_ones

array([2., 3., 4., 5., 6.])

In [23]:
array1 * new_ones

array([1., 2., 3., 4., 5.])

In [26]:
new_ones / array1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [27]:
new_ones // array1 #this will divide and floor the result values

array([1., 0., 0., 0., 0.])

In [28]:
array1 % 2 #remainder

array([1, 0, 1, 0, 1])

In [29]:
np.exp(array1) #exponential

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [30]:
np.log(array1) #log

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

### Aggregation

In [38]:
massive_array = np.random.random(100000)
massive_array[:10]

array([0.079009  , 0.39194377, 0.15755857, 0.70075838, 0.56362203,
       0.58579052, 0.27922046, 0.23152333, 0.46519497, 0.59638052])

Use NumPy Methods on NumPy Arrays and Python Methods on Python Arrays.

In [36]:
# Python Method to calculate Sum
%timeit sum(massive_array)

100 loops, best of 5: 17 ms per loop


In [37]:
# NumPy Method to calculate Sum
%timeit np.sum(massive_array) #425 times faster in this case than the Python Sum

The slowest run took 6.29 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 40 µs per loop


In [39]:
np.mean(massive_array)

0.500835229291351

In [40]:
# Standart Deviation
# Measure of how spread out a group of numbers is from the mean
# Sqrt of variance
np.std(massive_array)

0.288372633667325

In [42]:
# Variance
# Measure of the average degree to which each number is different to the mean
# Higher variance means wider range of numbers
# Lower variance means lower range of numbers
np.var(massive_array)

0.08315877584822923