In [1]:
import numpy as np

## 1. DataTypes and Attributes

In [4]:
#Main data type is ndarray (n-dimension array)
array1 = np.array([1,2,3,4,5])
type(array1)

numpy.ndarray

In [6]:
array2 = np.array([[1,2,3], [4,5,6]])
array2.shape

(2, 3)

In [13]:
array3 = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[13,14,15], [16,17,18]] ])
array3.shape

(3, 2, 3)

In [14]:
array1.ndim, array2.ndim, array3.ndim #number of dimensions of different arrays

(1, 2, 3)

In [10]:
array1.size, array2.size, array3.size #number of elements in different arrays

(5, 6, 18)

## 2. Creating Different kind of NumPy Arrays

In [11]:
sample_array = np.array([1,2,3])
sample_array.dtype

dtype('int64')

In [15]:
ones = np.ones(sample_array.shape) #replace all elements with 1
ones

array([1., 1., 1.])

In [17]:
zeros = np.zeros((2, 3)) #replace all element with 0. (2,3) is a given shape for the new array
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
ones.dtype, zeros.dtype #data type of ones and zeroes are float by default

(dtype('float64'), dtype('float64'))

In [20]:
range_array = np.arange(2, 10, 2) #parameters are: start_from, end_before, steps
range_array

array([2, 4, 6, 8])

In [21]:
random_array = np.random.randint(1, 10, size=(2,3)) #parameters: lowest_number(inclusive), highest_number(exclusive: n-1), size: row, column
random_array

array([[1, 8, 1],
       [4, 1, 6]])

In [22]:
random_array.shape

(2, 3)

In [23]:
random_array_2 = np.random.random((3, 4)) #only shape is passed as argument. low and high is 0.0 and 1.0 by default
random_array_2

array([[0.04815607, 0.29868555, 0.91814461, 0.20650593],
       [0.91627413, 0.68904956, 0.34118079, 0.78215435],
       [0.07959646, 0.47160716, 0.39171142, 0.1032644 ]])

In [25]:
random_array_3 = np.random.rand(3, 4) #same as before
random_array_3

array([[0.31168053, 0.53504602, 0.99057386, 0.51931616],
       [0.18281181, 0.81050135, 0.96430441, 0.57184246],
       [0.73049102, 0.06712821, 0.78590887, 0.76388864]])